added Chat api endpoints
SupportAI-Project/SupportAI-Backend pull request #3
Opened 2024-06-05 16:18 UTC by roiy0987

2024-06-06 09:24 UTC, JosephOri requested changes
your code looking good, need some changes

2024-06-06 09:24 UTC, JosephOri commented on src/chat/chat.service.ts
> +      newChat.status = 'open';
change `status` to boolean since its only have 2 states, also change its name to `isOpen`

2024-06-06 09:24 UTC, JosephOri commented on src/chat/dto/chat.dto.ts
> +  status?: string;
change `status` to a boolean called `isOpen`

2024-06-06 09:24 UTC, JosephOri commented on src/chat/entity/chat.model.ts
> +  status: string;
change status to a boolean called isOpen

2024-06-06 09:24 UTC, JosephOri commented on src/transcript/transcript.controller.ts
> +  // @Post('file')
please decide what to do with this code, we cant leave commented code, remove it or add it in the form you wanted it

2024-06-06 09:24 UTC, JosephOri commented on src/chat/entity/chat.model.ts
add here class-validator decorators, for more information : [https://docs.nestjs.com/techniques/validation](url)

2024-06-06 09:24 UTC, JosephOri commented on src/chat/chat.service.ts
> +    } catch (e) {
please add in every place in the code that you handle error a `Logger` to log the error to the screen, so the developer know where is the error, to see about this logger check out the code in the auth system code that is in my branch
 (auth-system-FP-11)

2024-06-06 09:24 UTC, JosephOri commented on src/transcript/transcript.service.ts
same here about error handling

2024-07-03 17:24 UTC, nitzanto requested changes

2024-07-03 17:24 UTC, nitzanto commented on libs/common/src/constants/errors/error.messages.ts
> +};
Could we separate these into different for files? For example, chat.error.message.ts , authentication.messages.ts

2024-07-03 17:30 UTC, nitzanto approved these changes

2024-07-03 20:58 UTC, JosephOri approved these changes

2024-07-03 20:58 UTC, merged